services:
  app:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - APP_ENV=development
      # Tell the app where Redis lives — using the service name as hostname
      - REDIS_HOST=redis
      # Tell your app where PostgreSQL lives using the service name as the host
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - OTEL_SERVICE_NAME=devops-lab-api
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_SAMPLE_RATE=1.0
      - GRAFANA_ENDPOINT=http://5.161.250.79:3000
      - INGEST_TELEMETRY=true
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - default
      - observability
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    # Database initialization configurations are entirely driven by env variables
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # The healthcheck dynamically uses the environment variables to authenticate
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  postgres_data:

networks:
  observability:
    name: observability-lab_default
    external: true
